accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path(r'signup/', views.SignUpView.as_view(), name='signup'),
    path(r'login/', views.CustomLoginView.as_view(), name="login"),
    path(r'logout/', auth_views.LogoutView.as_view(), name="logout"),
    #path(r'logout/', views.CustomLogoutView.as_view(), name="logout"),
]

moj_todo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views


handler403 = 'todo_app.views.access_denied'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo_app/', include('todo_app.urls')),
	#path(r'accounts/', include('django.contrib.auth.urls')),
	path(r'accounts/', include('accounts.urls')),
]

todo_app/urls.py
from django.urls import path

from . import views

app_name = 'todo_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.TableView.as_view(), name='table'),
    path('add_column/<int:pk>/', views.AddColumnView.as_view(), name='column_save'),
    path('add_task/<int:pk>/', views.AddTaskView.as_view(), name='task_save'),
    path('edit_task/<int:table_pk>/<int:pk>/', views.EditTaskView.as_view(), name='task_edit'),
    path('move_task/<int:pk>/', views.MoveTaskView.as_view(), name='move_task'),
    path('denied/', views.access_denied, name='denied')
]

todo_app/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse_lazy


class NamedModel(models.Model):
    """
    A model that has a name that is used to represent it (in __str__)
    """

    class Meta:
        abstract = True

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Table(NamedModel):
    """
    A todo table that contains columns used for organising task.
    Each table has it's own name (doesn't have to be unique) and
    a list of users that can access it.
    """

    users = models.ManyToManyField(User)

    def get_absolute_url(self):
        return reverse_lazy('todo_app:table', kwargs={'pk': self.pk})

class Column(NamedModel):
    """
    Each column belongs to a single table and has a name that doen't
    have to be unique. It is a container for tasks.
    """

    table = models.ForeignKey(Table, on_delete=models.CASCADE)



class Task(NamedModel):
    """
    A single task describes what has to be done via a name,
    a description and a deadline. More fields will probably be
    added in the future
    """

    column = models.ForeignKey(Column, on_delete=models.CASCADE)
    description = models.TextField()
    deadline = models.DateTimeField(null=True, blank=True)
    done = models.BooleanField(default=False)

    def is_near_to_deadline(self):
        """
        If a task's deadline is less than a day away it is considered
        near to it. This flag can be used to stress that fact on the
        website.
        """

        if self.deadline:
            now = timezone.now()
            near = now + datetime.timedelta(days=1) >= self.deadline
            return near and not self.done
        else:
            return False

todo_app/forms.py
from django.forms import ModelForm, DateTimeField
from .models import Task, Column
from bootstrap_modal_forms.forms import BSModalForm

class ColumnForm(ModelForm):
	class Meta:
		model = Column
		exclude = ['table']

class TaskFrom(ModelForm):
	class Meta:
		model = Task
		exclude = ['column']

class TaskEditForm(BSModalForm):
    """
    Temporary form for testing BSModal libray. Probably can be merged with TaskFrom later. 
    """
    class Meta:
        model = Task
        exclude = ['column']

todo_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.base import TemplateResponseMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import JsonResponse
from django.core.exceptions import PermissionDenied

from .models import Table, Column, Task
from .forms import ColumnForm, TaskFrom, TaskEditForm
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.http import HttpResponse
from django.template.loader import render_to_string


class CheckedTable(UserPassesTestMixin):
    """
    This view checks whether a table with the given pk exists
    and if it does and the user currently logged in has access
    to otherwise a PermissionDenied exception is raised with 
    the appropriate message
    """

    not_exist_msg = "Table does not exist"
    not_allowed_msg = "You are not allowed to access this table"

    def test_func(self):
        if 'table_pk' in self.kwargs:
            pk = self.kwargs['table_pk']
        else:
            assert 'pk' in self.kwargs
            pk = self.kwargs['pk']

        try:
            curr_table = Table.objects.get(pk=pk)
            if self.request.user not in curr_table.users.all():
                raise PermissionDenied(self.not_allowed_msg)
        except Table.DoesNotExist:
            raise PermissionDenied(self.not_exist_msg)

        return True


class IndexView(TemplateResponseMixin, View):
    """
    A simple view that displays tables that belong to the user
    """

    template_name = 'todo_app/tables.html'

    def get(self, request):
        table_list = [x for x in Table.objects.all() if request.user in x.users.all()]
        task_list = Task.objects.all()

        context = {'table_list': table_list, 'table_remind_list': table_list, 'task_remind_list' : task_list}
        return self.render_to_response(context)


class TableView(TemplateResponseMixin, CheckedTable, View):
    """
    A simple view that display all tasks in a table that belong to the user
    """

    template_name = 'todo_app/table.html'
    not_allowed_msg = "You are not allowed to view this table"

    def get(self, request, pk):
        table_remind_list = [x for x in Table.objects.all() if request.user in x.users.all()]
        task_remind_list = Task.objects.all()

        curr_table = Table.objects.get(pk=pk)
        column_form = ColumnForm()
        task_form = TaskFrom()
        column_list = Column.objects.filter(table__pk=pk)
        task_list = Task.objects.filter(column__table__pk=pk).order_by('-deadline')
        context = {'user': request.user, 'page_title': curr_table.name, 'table_remind_list': table_remind_list, 'task_remind_list' : task_remind_list, 'column_list': column_list, 'column_form': column_form, 'task_form': task_form, 'tab_id': pk}
        
        return self.render_to_response(context)


class AddColumnView(CheckedTable, View):
    """
    A temporary view that handles POST method
    Source: ColumnForm
    """

    not_allowed_msg = "You are not allowed to add to this table"

    def post(self, request, pk):
        table = Table.objects.get(pk=pk)
        column = Column(table=table)
        form = ColumnForm(request.POST, instance=column)
        if form.is_valid():
            form.save()
        
        return redirect(reverse_lazy('todo_app:table', kwargs={'pk': pk}))


class AddTaskView(CheckedTable, View):
    """
    A temporary view that handles POST method
    Source: ColumnForm
    """

    not_allowed_msg = "You are not allowed to add to this table"

    def post(self, request, pk):
        table = Table.objects.get(pk=pk)
        # TODO: Check if the key is present
        column = Column.objects.get(pk=int(request.POST.get('column')))
        if column.table.pk != pk:
            raise PermissionDenied("Table id dont's match (org:%d,target:%d)" % (column.table.pk, pk))
        
        form = TaskFrom(request.POST, instance=Task(column_id=column.id))

        if form.is_valid():
            form.save()

        return redirect(reverse_lazy('todo_app:table', kwargs={'pk': pk}))


class MoveTaskView(CheckedTable, View):
    """
    A temporary view that handles POST method
    Source: ColumnForm
    """

    not_allowed_msg = "You are not allowed to move tasks in this table"

    def post(self, request, pk):
        data = {}

        # TODO: Check if the keys are present and if no 404 arises
        task = Task.objects.get(pk=int(request.POST.get('task')))
        target = Column.objects.get(pk=int(request.POST.get('target')))

        # Checking if the origin and target columns are in the same table
        if task.column.table == target.table and target.table.pk == pk:
            # Move task
            task.column = target
            task.save()

            data['success'] = True
            data['url'] = reverse_lazy('todo_app:table', kwargs={ 'pk': target.table.pk })
        else:
            # Send error
            data['success'] = True
            data['msg'] = "The origin and target tables are not the same"
        
        return JsonResponse(data)


class EditTaskView(CheckedTable, BSModalUpdateView):
    """
    BSModal view of edit form
    """
    template_name = 'todo_app/modal/edit_task.html'
    model = Task
    form_class = TaskEditForm
    #success_url = reverse_lazy('index')
    success_message = 'success'
    def get_success_url(self):
        return reverse_lazy('todo_app:table', args = (self.object.column.table.pk,))


def access_denied(request, exception):
    table_list = [x for x in Table.objects.all() if request.user in x.users.all()]
    task_list = Task.objects.all()

    context = {'page_title': "Access denied", 'page_subtitle': exception, 'table_remind_list': table_list, 'task_remind_list' : task_list}

    return render(request, 'todo_app/access_denied.html', context)

todo_app/templates/todo_app/access_denied.html
{% extends "todo_app/main_base.html" %}

{% block content %}
<div class="container">
    <div class="col-lg-9">
      <h1 class="my-4">{{ page_title }}</h1>
      <h2 class="my-4">{{ page_subtitle }}</h2>
    </div>
  </div>
{% endblock %}

todo_app/templates/todo_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Homepage - Start Bootstrap Template</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body style="padding-top: 56px;">
  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <h1 class="my-4">Nasze TO-DO</h1>
      </div>
      <div class="col-lg-9">
        <div class="row">
		{% for task in task_list %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">{{ task.name }}</a>
                </h4>
                <h5>{{ task.deadline }}</h5>
                <p class="card-text">{{ task.description }}</p>
              </div>
            </div>
          </div>
		{% endfor %}
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

</body>

</html>

todo_app/templates/todo_app/main_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% if page_title %}{{ page_title }} - {% endif %}mojeTODO</title>
  <link rel="stylesheet" type="text/css" href="{% static 'todo_app/style.css' %}">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
  <!-- jQuery CDN - Full version (=with AJAX) -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <!-- Popper.JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <!-- Bootstrap core JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  <!-- jQuery Custom Scroller CDN -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
  <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
  
</head>
<body>
  <div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
      <h2 class="py-4 m-0 sidebar-header"><a href="{% url 'todo_app:index' %}" class="text-white">mojeTODO</a></h2>

      <h4 class="border-top m-0 sidebar-subheader">Deadlines:</h4>
      {% for tab in table_remind_list %}
      <div class="card bg-transparent my-0 border-bottom-0 rounded-0">
        <div class="card-body p-0">
          <div class="card-header">
            <h5 class="m-0"><a href="{% url 'todo_app:table' tab.id %}" class="text-white">{{ tab.name }}</a></h5>
          </div>
          <ul class="list-group list-group-flush py-2">
            {% for task in task_remind_list %}
            {% if task.column.table == tab and task.is_near_to_deadline %}
            <li class="mx-auto">{{ task.name }}<br/>{{ task.deadline }}</li>
            {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
      {% endfor %}
    </nav>
    <!-- Sidebar's end  -->


    <!-- Page Content  -->
    
    <div id="content" class="p-0">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      
        <div class="container-fluid">

          <button type="button" id="sidebarCollapse" class="btn btn-info">
            <i class="fas fa-align-left"></i>
            <span id="sidebarCollapseButton">Show menu</span>
          </button>
          <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item active">
                <p class="nav-link m-0">Logged in as <strong>{{ user.username }}</strong></p>
              </li>
              <li class="nav-item active">
                <a class="btn btn-info" href="{% url 'accounts:logout' %}?next={% url 'todo_app:index' %}">Log out</a>
              </li>
              {% else %}
              <li class="nav-item active">
                <button class="login btn btn-info mr-1">Login</button>
              </li>
              <li class="nav-item active">
                <button class="signup btn btn-info">Sing up</button>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      {% block content %}{% endblock %}
    </div>
  </div>



  {% block extras %}{% endblock %}

  <script type="text/javascript">
    function sidebarCollapseButtonTextToggle() {
      var button = $("#sidebarCollapseButton");
      var text = $('#sidebar, #content').hasClass('active') ? "Show menu" : "Hide menu";
      button.text(text);
    }

    $(document).ready(function () {

      $("#sidebar").mCustomScrollbar({
         theme: "minimal"
      });
      $('#sidebarCollapse').on('click', function () {
        $('#sidebar, #content').toggleClass('active');
        sidebarCollapseButtonTextToggle();
      });
    });

    sidebarCollapseButtonTextToggle();
  </script>

  {% if messages %}  
  <div aria-live="polite" aria-atomic="true" style="position: relative;">
    <div style="position: absolute; left: 250px;">
      {% for message in messages %}
      <div class="toast ml-2 mt-2" role="alert" aria-live="assertive" aria-atomic="true" data-delay="2500">
        <div class="toast-header">
          <!-- <img src="..." class="rounded mr-2" alt="..."> -->
          <strong class="mr-auto">Message</strong>
          <!-- <small>11 mins ago</small> -->
          <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="toast-body">
          {{ message }}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}

  <script>
    $('.toast').toast('show');
  </script>

{% block accounts-modals %}

  <!-- Sign-up modal -->
  {% include "todo_app/modal/empty.html" %}
  <script>
    $(document).ready(function() {
      $(".signup").modalForm({
        formURL: "{% url 'accounts:signup' %}"
      });
      $(".login").modalForm({
        formURL: "{% url 'accounts:login' %}"
      });
    });

  </script>

{% endblock %}

</body>

</html>

todo_app/templates/todo_app/table.html
{% extends "todo_app/main_base.html" %}

{% block content %}
{% load todo_extra %}

<div class="container">
    <div class="col-lg-9">
      <h1 class="my-4">{{ page_title }}</h1>
    </div>
    {% if not denied %}
    <div class="row">
      {% for col in column_list %}
      {% with next=column_list|next_elem:forloop.counter0 %}
      {% with prev=column_list|prev_elem:forloop.counter0 %}
      <div class="card mx-2">
        <div class="card-header">
          {{ col.name }}
        </div>
        <div class="card-body text-center p-2">
          {% for task in col.task_set.all %}
          <div class="card text-left {% if forloop.last %}mb-0{% else %}mb-2{% endif %}">
            <div class="card-body">
              <h5 class="card-title">{{ task.name }}</h5>
              {% if task.deadline %}<h6 class="card-subtitle mb-2 {% if task.is_near_to_deadline %}text-danger{% else %}text-muted{% endif %}">Deadline: {{ task.deadline }}</h6>{% endif %}
              <p class="card-text">{{ task.description }}</p>
              <button type="button" class="edit-task btn btn-link p-0" data-toggle="modal" data-target="#taskEditModal" data-task="{{ task.id }}" data-id="{% url 'todo_app:task_edit' col.table.id task.pk %}">Edit</button>
              {% if not forloop.parentloop.first %}<button type="button" class="btn btn-link p-0 ml-2 move-button" onclick="moveTask('{% url 'todo_app:move_task' col.table.id %}', {{ task.id }}, {{ prev.id }})">Move left</a>{% endif %}
              {% if not forloop.parentloop.last %}<button type="button" class="btn btn-link p-0 ml-2 move-button" onclick="moveTask('{% url 'todo_app:move_task' col.table.id %}', {{ task.id }}, {{ next.id }})">Move right</a>{% endif %}
            </div>
          </div>
          {% endfor %}
          <div>
            <button type="button" class="btn btn-primary mx-auto mt-2" data-toggle="modal" data-target="#taskModal" data-column="{{ col.id }}">New task</button>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endwith %}
      {% endfor %}
      <div>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#columnModal">New column</button>
      </div>
    </div>
    {% endif %}
  </div>
{% endblock %}

{% block extras %}
  <!-- New column modal -->
  {% url 'todo_app:column_save' tab_id as columnActionUrl %}
  {% include "todo_app/modal/modal_form.html" with modal_name="New column" modal_id="columnModal" action=columnActionUrl form=column_form %}

  <!-- New task modal -->
  {% url 'todo_app:task_save' tab_id as taskActionUrl %}
  {% include "todo_app/modal/task.html" with modal_name="New task" modal_id="taskModal" action=taskActionUrl form=task_form columd_id="id_column" %}

  <!-- Edit task modal -->
  {% include "todo_app/modal/empty.html" %}

  {% csrf_token %}
  <script>
    function moveTask(url, task_pk, target_pk) {
      console.log("Moving task", task_pk, "to column", target_pk)

      var token = $('input[name=csrfmiddlewaretoken]').val()
      console.log("token", token)

      $.post(url, {
          csrfmiddlewaretoken: token,
          task: task_pk,
          target: target_pk
      }).done(function(data) {
          if (data['success']) {
            console.log("Success", data)
            window.location = data['url']
          } else {
            console.log("Error", error)
          }
      }).fail(function(error) {
          console.log("Error", error)
      })
    }
    
    $(document).ready(function() {
      $(".edit-task").each(function () {
        $(this).modalForm({
          formURL: $(this).data('id'),
          modalContent: ".modal-content-ajax",
        });
      });
    });
    </script>
{% endblock %}

todo_app/templates/todo_app/tables.html
{% extends "todo_app/main_base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    {% if user.is_authenticated %}
    <div class="col-lg-9">
      <h1 class="my-4">Your tables</h1>
    </div>
    <div class="col-lg-9">
      <div class="row">
        {% for tab in table_list %}
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card h-100">
            <div class="card-body">
              <h4 class="card-title">
                <a href="{% url 'todo_app:table' tab.id %}">{{ tab.name }}</a>
              </h4>
            </div>
          </div>
        </div>
        {% endfor %}
        <div class="col-md-6">
          <a href="#" class="btn btn-primary">New table</a>
        </div>
      </div>
    </div>
    {% else %}
    <div class="col-lg-9">
      <h1 class="my-4">Log in to manage your tables</h1>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block extras %}
{% endblock %}